<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE doc [
<!NOTATION cmark SYSTEM "CommonMark">
<!NOTATION z SYSTEM "Z e-mail mark-up">
<!ELEMENT doc (p | list | mark-up)* >
<!ELEMENT list (li)+ >
<!ELEMENT p (#PCDATA | list)* >
<!ELEMENT li (#PCDATA | list)* >
<!ELEMENT mark-up (#PCDATA)>
<!ATTLIST mark-up syntax NOTATION (z|cmark) #REQUIRED
                  mode   (block|inline)     #IMPLIED>
<!ENTITY xml "&amp;lt;XML&amp;gt;">
]>
<doc>
    <p>Sample &xml; document</p>
    <list>
	<li>No reference to external DTD.</li>
	<li>All elements declared in internal subset</li>
    </list>
    <p>This should be easy!</p>
<mark-up syntax="cmark"><!-- We *must* use quotes here for XML -->
<![CDATA[
Using CommonMark
================

We can use _CommonMark_ syntax *inside* a `<mark-up>` element,
but we must take care to avoid to accidentally use
&xml; mark-up: eg, place the script inside a `CDATA`
section.
Here is an `<mark-up>` element containing C source code:
]]></mark-up>
<mark-up syntax="C">
int main(void)
{
  printf("Hello world!\n");
  return 0;
}
</mark-up>

<p>Here is an example in Z Notation:</p>
<mark-up syntax="z">
+-- Name ---
    n : %N
|--
    %E m : %N | m > n
---
</mark-up>
    <p>That ends our little example.</p>
</doc>

